const MAX_PLAYERS = 8;
const MIN_PLAYERS = 2;
const TURN_TIMEOUT_MS = 90000;
const RECONNECT_TIMEOUT_MS = 60000;
const ROOM_CODE_LENGTH = 6;
const REVOLVER_CHAMBERS = 6;

const ROOM_STATE = {
  WAITING: 'waiting',
  IN_GAME: 'in_game',
  FINISHED: 'finished',
};

const DEFAULT_SETTINGS = {};

module.exports = {
  MAX_PLAYERS,
  MIN_PLAYERS,
  TURN_TIMEOUT_MS,
  RECONNECT_TIMEOUT_MS,
  ROOM_CODE_LENGTH,
  ROOM_STATE,
  DEFAULT_SETTINGS,
  REVOLVER_CHAMBERS,
};
